-- ─────────────────────────────────────────────────────────────────────────────
-- DecentraLicense — Database Migration 001
-- Table: trading_subscriptions
--
-- Run this in: Supabase Dashboard → SQL Editor → New Query → Run
-- Or via Supabase CLI: supabase db push
-- ─────────────────────────────────────────────────────────────────────────────

-- ── Enable required extensions ────────────────────────────────────────────────
-- pgcrypto provides gen_random_uuid() for UUID primary keys
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ── Create the table ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS trading_subscriptions (
    -- Primary key: UUIDv4, generated by the database
    id                UUID            PRIMARY KEY DEFAULT gen_random_uuid(),

    -- The buyer's EVM wallet address (lowercase, unique constraint)
    -- We store normalized (lowercase) to allow case-insensitive lookups
    wallet_address    TEXT            NOT NULL,

    -- The generated license key in TRD-XXXX-XXXX-XXXX-XXXX format
    license_key       TEXT            NOT NULL,

    -- Which token was used to pay (e.g. "USDT-BEP20")
    token_used        TEXT            NOT NULL DEFAULT 'USDT-BEP20',

    -- When the subscription expires (set to now() + 30 days on creation)
    expires_at        TIMESTAMPTZ     NOT NULL,

    -- Whether the subscription is currently active
    -- Flipped to false automatically by /api/check-license on expiry
    is_active         BOOLEAN         NOT NULL DEFAULT TRUE,

    -- Record creation timestamp (immutable — never updated)
    created_at        TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

-- ── Unique constraints ────────────────────────────────────────────────────────

-- One subscription record per wallet (renewal updates the same row)
CREATE UNIQUE INDEX IF NOT EXISTS idx_trading_subscriptions_wallet
    ON trading_subscriptions (LOWER(wallet_address));

-- License keys must be globally unique
CREATE UNIQUE INDEX IF NOT EXISTS idx_trading_subscriptions_license_key
    ON trading_subscriptions (license_key);

-- ── Performance indexes ───────────────────────────────────────────────────────

-- Used by /api/check-license for primary key lookup
CREATE INDEX IF NOT EXISTS idx_trading_subscriptions_is_active
    ON trading_subscriptions (is_active);

-- Composite index for expiry cleanup queries
CREATE INDEX IF NOT EXISTS idx_trading_subscriptions_expires_active
    ON trading_subscriptions (expires_at, is_active)
    WHERE is_active = TRUE;

-- ── Row Level Security (RLS) ──────────────────────────────────────────────────
-- Enable RLS — our service role key bypasses RLS, so only the API can read/write.
-- No anonymous or authenticated user can access this table via the client-side SDK.

ALTER TABLE trading_subscriptions ENABLE ROW LEVEL SECURITY;

-- Block all access by default (service role bypasses this — API routes only)
-- This ensures frontend code cannot query the DB even if the anon key leaks
CREATE POLICY "No direct access" ON trading_subscriptions
    FOR ALL
    TO anon, authenticated
    USING (FALSE);

-- ── Comments ──────────────────────────────────────────────────────────────────
COMMENT ON TABLE trading_subscriptions IS
    'Stores on-chain verified software subscriptions issued via BNB Smart Chain USDT payments.';

COMMENT ON COLUMN trading_subscriptions.wallet_address IS
    'EVM wallet address of the buyer, stored in lowercase. Unique per row.';

COMMENT ON COLUMN trading_subscriptions.license_key IS
    'Cryptographically generated key in TRD-XXXX-XXXX-XXXX-XXXX format.';

COMMENT ON COLUMN trading_subscriptions.token_used IS
    'Identifier for the payment token used (e.g., USDT-BEP20).';

COMMENT ON COLUMN trading_subscriptions.expires_at IS
    'UTC timestamp of subscription expiry. Compared against server time in /api/check-license.';

COMMENT ON COLUMN trading_subscriptions.is_active IS
    'Flipped to false by /api/check-license when expires_at has passed.';

-- ── Verification query (run to confirm migration succeeded) ───────────────────
-- SELECT column_name, data_type, is_nullable
-- FROM information_schema.columns
-- WHERE table_name = 'trading_subscriptions'
-- ORDER BY ordinal_position;
