-- ─────────────────────────────────────────────────────────────────────────────
-- Migration 003 — Payment invoices for Scan-To-Pay (EIP-681 QR) checkout
-- Run AFTER 001_trading_subscriptions.sql and 002_products_and_admin.sql
--
-- Flow:
--   buyer clicks "Pay with <wallet>" → server creates a payment_invoices row with a
--   UNIQUE amount (base price + tiny random cent surcharge). The QR / copyable
--   payment URI is generated by the API (src/lib/eip681.ts).
--   Buyer scans the QR with their wallet's own QR scanner and approves the
--   ERC-20 transfer. The frontend then polls GET /api/invoices/[id]; the server
--   scans BSC logs for a Transfer to the admin wallet matching exactly this
--   amount. Because each invoice amount is unique, the payment is matched even
--   though we never learned the buyer's wallet address in advance.
-- ─────────────────────────────────────────────────────────────────────────────

-- ── payment_invoices ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS payment_invoices (
    id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Which product the invoice is for
    product_id       TEXT        NOT NULL REFERENCES products(id),

    -- Expected payment in wei (18 decimals, BSC USDT). Includes the unique
    -- surcharge so one admin wallet can serve many concurrent checkouts.
    amount_wei       NUMERIC(40) NOT NULL,

    -- Human-readable display amount (we clamp to 6 decimals)
    amount_label     TEXT        NOT NULL,

    -- Block height at invoice creation time — scan starts here to keep the
    -- RPC log window small and bounded
    scan_from_block  BIGINT      NOT NULL,

    -- status: 'pending' | 'paid' | 'expired'
    status           TEXT        NOT NULL DEFAULT 'pending',

    -- Filled in when the on-chain payment is detected (paid)
    wallet_address   TEXT,
    tx_hash          TEXT,
    license_key      TEXT,
    expires_at       TIMESTAMPTZ,

    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_invoices_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_payment_invoices_status_created
    ON payment_invoices (status, created_at);

CREATE INDEX IF NOT EXISTS idx_payment_invoices_paid_by_wallet
    ON payment_invoices (wallet_address)
    WHERE wallet_address IS NOT NULL;

-- Prevent two pending invoices from reusing the same unique amount
CREATE UNIQUE INDEX IF NOT EXISTS idx_payment_invoices_pending_amount
    ON payment_invoices (amount_wei)
    WHERE status = 'pending';

-- ── RLS ───────────────────────────────────────────────────────────────────────
ALTER TABLE payment_invoices ENABLE ROW LEVEL SECURITY;

CREATE POLICY "No direct access" ON payment_invoices
    FOR ALL
    TO anon, authenticated
    USING (FALSE);

COMMENT ON TABLE payment_invoices IS
    'One row per unpaid scan-to-pay request. The unique amount identifies the payment on-chain.';
COMMENT ON COLUMN payment_invoices.amount_wei IS
    'Expected payment in wei (18 decimals). Base price + random cent surcharge for uniqueness.';